// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT8GOvhZYTWLCkGNGfrb3xFE0ziE5tNXw',
    appId: '1:99191920886:web:69b55c65f4722a39e7f4d7',
    messagingSenderId: '99191920886',
    projectId: 'shoecomm-80157',
    authDomain: 'shoecomm-80157.firebaseapp.com',
    storageBucket: 'shoecomm-80157.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfVB_iTJTFawAMjRU5xVPMSvXsyJWeTeU',
    appId: '1:99191920886:android:501e2e1a5c6b3a00e7f4d7',
    messagingSenderId: '99191920886',
    projectId: 'shoecomm-80157',
    storageBucket: 'shoecomm-80157.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_m2IJL-2v1pg8ThdX6t187SFebVP_Fsg',
    appId: '1:99191920886:ios:a0529d41b3e5eaeee7f4d7',
    messagingSenderId: '99191920886',
    projectId: 'shoecomm-80157',
    storageBucket: 'shoecomm-80157.firebasestorage.app',
    iosBundleId: 'com.example.shoecomm',
  );
}
